(module
  ()
  (def id (u)
    (pi T imp (sort (univsucc (univzero)))
      (pi x ex (bound 0)
        (bound 1)))
    (lam T imp (sort (univsucc (univzero)))
      (lam x ex (bound 0)
        (bound 0)))
  )
  (ind Bool () () (sort (univsucc (univzero))) (
    (true (inst (Bool) ()))
    (false (inst (Bool) ()))
  ))
)
